### ISSUE TITLE
Obtaining Beverton-Holt parameters from FishLife

### ISSUE THREAD

**Issue by srfung** [James-Thorson-NOAA/FishLife#15]
I've been trying to obtain the alpha and beta parameters for a standard Beverton-Holt recruitment equation from the FishLife package.  I've been following the tutorial vignette but it's not obvious to me which of the outputs is related to the BH parameters I'm looking for.

I've included a screen shot of the outputs I've been able to get.

![FishLife Screenshot](https://user-images.githubusercontent.com/60474331/91052739-e16a3580-e5ef-11ea-9024-528386aa5144.jpg)

Thanks,
Simon

**Comment by James-Thorson-NOAA** [comment]
I have edited the wiki mainpage to respond in general:  https://github.com/James-Thorson-NOAA/FishLife#extract-other-values

To your specific questions:
- I argue in Thorson ([2020](https://doi.org/10.1111/faf.12427)) that density dependence is not exchangable without standardizing for something like stock area;
- The alpha is not unit-invariant, whereas natural-log of maximum-annual-spawners-per-spawner (ln_MASPS) is more exchangeable.  So you can calculate slope at the origin given the units you're using from either steepness of ln_MASPS for a given stock.

I'd be happy to chat more specifics about your goals by email, or general questions here on the issue tracker. and please close the issue if this is sufficient for now

**Comment by srfung** [comment]
Thanks for the reply.  I'll send you an email for my specific problem so it doesn't clutter up your github.
