### ISSUE TITLE
Errors from fresh installation of FishLife

### ISSUE THREAD

**Issue by Johnausfisher** [James-Thorson-NOAA/FishLife#18]
I had help today installing a fresh R environment on my computer and the Fishlife package.
However we ran into trouble with the Error: 'fishbase' is not an exported object from 'namespace:rfishbase'.
I understand that you may be aware of this issue for users of Fishlife. Are you able to elaborate on the situation and advise if there is a work around for this problem that is practical for a novice like myself?

**Comment by shcaba** [comment]
Do you have the rfishbase package installed?
Sometimes dependencies don't always get installed along with the featured package. 
I suspect for some reason it did not install rfishbase.
try install.packages('rfishbase') and see if that gets you past the error.

-Jason

**Comment by James-Thorson-NOAA** [comment]
I think the issue is that `rfishbase` removed the object in its recent releases, as I raised in an [issue on their tracker](https://github.com/ropensci/rfishbase/issues/240).  I need to do some work to keep updated on their changes, but am hoping to get an update from them first.  In the meantime, I recommend manually downloading an older `rfishbase` release as ZIP file (perhaps 3.0.4) and installing that locally.  Hopefully I'll hear from them soon and can then make more long-term of a fix.

**Comment by shcaba** [comment]
I can confirm that moving from the new to an older (3.x) rfishbase version will do the trick. 
Jim, is it worth zipping a version that works and putting it on this website for users? I am happy to provide that zipped file it that is easiest.

**Comment by Johnausfisher** [comment]
I would appreciate that access to a zipped file for version 3.x rfishbase because I haven't been able to find a connection to one so far. Do I have to remove the version 4.0 installation of rfishbase before installing version 3.x?

**Comment by shcaba** [comment]
Send me an email at jason.cope@noaa.gov and I can send you a zipped version of rfishbase and let you know how to replace what you have installed.

**Comment by Johnausfisher** [comment]
Thanks Jason. The 3.X version of rfishbase certainly did the trick. I also needed to install arkdb in my case.

**Comment by James-Thorson-NOAA** [comment]
Thank you both for alerting me to this issue, and @cboettig for discussing [the issue](https://github.com/ropensci/rfishbase/issues/240#issuecomment-1003861089).  I have just made published FishLife release 2.0.1 on main branch, which requires a version of `rfishbase` prior to release 4.0.0 when taxa-table `fishbase` was replaced with function `load_taxa`.  I hope to use the `load_taxa` during my next FishLife development update

**Comment by Amidu-mans** [comment]
Hi James, I am a user of FishLife and it use to walk nicely, but of recent, I tried to run a stock and got the following error: "fishbase' is not an exported object from 'namespace:rfishbase".  I will greatly appreciate if help is provided me. Thanks, looking forward.

**Comment by James-Thorson-NOAA** [comment]
Do you get an terminal message when loading the package via `library(FishLife)`?  If so, what does it say?

**Comment by Amidu-mans** [comment]
Thank you so much, Jim,
The problem has solved. I just followed the terminal message you alerted me
of. I reinstalled and everything is working fine. Please bear with me. I am
a beginner but fast learner.

**Comment by James-Thorson-NOAA** [comment]
No worries at all!  Just couldn't remember what it said :)  I'll look to see if I can streamline it a bit.  please also look at the "Articles" here for [usage examples](https://james-thorson-noaa.github.io/FishLife/)

**Comment by Amidu-mans** [comment]
Oh, I see!

At first load, a terminal message warning to install updated version. But
if you ignore the warning and reload library it will then load perfect
without warning but it will not work instead the error I reported will
appear.


But now everything is working fine!

Thank you for the documents.
