### ISSUE TITLE
Life history traits not available for "non-fish" species like crustaceans and cephalopods

### ISSUE THREAD

**Issue by realsmak88** [James-Thorson-NOAA/FishLife#19]
Hey Jim,
I was trying to use the SPMpriors package to generate priors for a shrimp species (Parapenaeus longirostris) but it failed. It seems that this package is linked to Fishlife or maybe to Fishbase database which is dedicated to finfish species contrairly to Sealifebase (https://www.sealifebase.ca/) which has life history data for other species like crustaceans, cephalopods, etc.
Is it possible to fix this issue ?

Thanks in advance

**Comment by James-Thorson-NOAA** [comment]
I'd *love* to link it to invertebrates, and in fact have written a grant to do so with Deng Palomeres, Aurore Maureaud and others (it wasn't funded).  It requires some dedicated effort to identify what traits to use, and presumably run in phylogenetic batches where those traits are well defined.  Please email me if you have time to collaborate on this, or ideas for how to identify funding.
