### ISSUE TITLE
How to update prediction DB to use latest FishBase species data?

### ISSUE THREAD

**Issue by dtickler-MF** [James-Thorson-NOAA/FishLife#25]
Hi there,

We are using the predicted/standardised life history parameters from FishLife as an input to a model to link life-history and fishery context to stock status, but are missing a number of important species (e.g. _Strangomera bentincki_) which are in the latest version of FishBase, but not the 2016 version used to train the published FishLife model.

Is it possible to update the predictions database _en masse_ by passing the model a new version of FishBase, and if yes, what needs to be done (in terms of variable renaming, etc.) to the downloaded FishBase data for this process to work?

Many thanks for any pointers on this - the update_predictions() function seems to be what I'm looking for, but unclear how to use this with a new Fishbase DB.

Best regards,

David

**Comment by James-Thorson-NOAA** [comment]
Please feel free to email me to discuss by videochat.  

There's a few paths forward:

- you could refit the entire `FishLife` model using the materials in github, although it's not super-well documented, so presumably would take some effort.
- if ignoring the stock-recruit component (and resulting steepness, intrinsic growth rate, and generation time), you could use [phylosem](https://cran.r-project.org/web/packages/phylosem/index.html), as described [here](https://doi.org/10.1111/faf.12800), which is my effort to make a simple-to-use version of FishLife
- Ultimately, I think agencies have under-invested for decades in systematic trait-imputation (including phylogenetic trait imputation), and would love to collaborate on a FishTraits initiative to (in parallel) compile, impute, and distribute imputed traits.

closing for now, but happy to discuss :)
